### ISSUE TITLE
Use dimension/level role for date/time dimension

### ISSUE THREAD

**Issue by Stiivi** [jjmontesl/cubesviewer#22]
Suggestion: In cubes 1.0 there is a new dimension and level metadata called "role". Date/time dimensions have `role == "time"` and levels have respective calendar unit names, such as `year`, `month`, ... It would be nice if the cubes viewer uses this information.

The roles for date/time dimension levels are guaranteed to be provided from the server, even if it is not explicitly specified in the model, if the level names match the calendar unit names.

**Comment by jjmontesl** [comment]
Fixed (though not extensively tested, will require review) on a0c2f2d9ba71dee51f60c4ac44297f9e8ca120ce , leading to 0.10.
