### ISSUE TITLE
Trouble with Cuts in serializedview

### ISSUE THREAD

**Issue by psychok7** [jjmontesl/cubesviewer#35]
Hi there, i am having some trouble using the `cuts` feature on a `serializedView` to force a certain filtering.

i have 

```
        var serializedView = {
            "cubename":"products_ordersproductsoffers", "name":"Cube View",
            "mode":"series",
            "drilldown":[
                "id", "user", "products", "resources"
            ],
            "cuts":[{"id":"184"}],
            "yaxis":"unitary_price_sum"
        };
```

i have tried both `"cuts":[{"id":"184"}],` and `"cuts":["id:184"],` and no luck

What am i doing wrong??

cheers

**Comment by jjmontesl** [comment]
Cuts are serialized (as an array of cut elements) using the following syntax:

```
"cuts": [
    {"dimension":"customer","value":"123_Warehousing"}
]
```

Alternatively, you can use the full CubesViewer app to design the view, and then click on "Panel / Serialize" serialize it.

The method that adds a cut, from Javascript, is `cubesviewer.view.cube.explorer.selectCut(view, dimension, value)` at https://github.com/jjmontesl/cubesviewer/blob/master/src/web/static/js/cubesviewer/cubesviewer.views.cube.explore.js#L665 and it contains code that pushes the information into `view.params`. 

```
view.params.cuts.push({
    "dimension" : dimension,
    "value" : value
});
```

Anyway, unless you need to programatically change cuts, I'd rather use CubesViewer to design the view, then serialize it with the Serialize menu option.

**Comment by psychok7** [comment]
@jjmontesl  thanks. i really need to define my own custom cuts.
