### ISSUE TITLE
Issues with dimension filter

### ISSUE THREAD

**Issue by psychok7** [jjmontesl/cubesviewer#37]
This might be an enhancement but here it goes:

Basically when i filter a dimension like in the screenshot if i get like 10 or more search results its not very practical to be clicking each one.

Maybe have an extra button so only select the filtered results all at once?? If you guide me to the proper place in the code maybe i can even write this enhancement on my own

![screen](https://cloud.githubusercontent.com/assets/282284/6274207/c1520ac6-b86d-11e4-916e-97bef69f8457.png)

**Comment by psychok7** [comment]
I am now really a Javascript guy but this is a temporary workaround i found. Unfortunately it does not work well when dealing with Case Insensitive searches:

```
		$(view.container).find(".cv-views-dimensionfilter-selectall").button().click(function() {
			//$(view.container).find(".cv-view-dimensionfilter-list").find(":checkbox").not(":checked").trigger('click');;
            // Clear previous selected items
            $(view.container).find(".cv-view-dimensionfilter-list").find(":checkbox").filter(":checked").trigger('click');
            var search_value = $( "input[name='dimensionfilter-list-search']" ).val();
            var filtered_checkboxes = "input[type='checkbox'][value^=" + search_value +"]";
            $(view.container).find(".cv-view-dimensionfilter-list").find(filtered_checkboxes).trigger('click');
		});
```

**Comment by psychok7** [comment]
I think i got it. So this ended up being the code i altered:

````
		$(view.container).find(".cv-views-dimensionfilter-selectall").button().click(function() {
            // Clear previous selected items
            $(view.container).find(".cv-view-dimensionfilter-list").find(":checkbox").filter(":checked").trigger('click');
            $(view.container).find(".cv-view-dimensionfilter-list").find(":checkbox:visible").trigger('click');
		});
```

Does this seem ok??

**Comment by jjmontesl** [comment]
Merged and closing.
