### ISSUE TITLE
String with hyphen sign cause dimension filter work unexpectedly

### ISSUE THREAD

**Issue by asakous** [jjmontesl/cubesviewer#39]
string with hyphen sign can't use dimension filter. it's always return 0 on web browser.

**Comment by jjmontesl** [comment]
This looks like a bug. Hyphens shall be escaped using `\` as per https://pythonhosted.org/cubes/server.html#special-characters .

I will review this for next version.

**Comment by jjmontesl** [comment]
This shall be fixed by a65f40517721e5ef8da7bda90928d1db5b8d6a6f . Pending verification once 2.0 is out.

**Comment by jjmontesl** [comment]
Please test on your side with 2.0 and report if you hit any problem.
