### ISSUE TITLE
How to sort the date result

### ISSUE THREAD

**Issue by frogy** [jjmontesl/cubesviewer#43]
Hi, Sir,
I tried your cubesviewer to OLAP our Mac Store data. This is quite friendly and powerful. Here I met one problem. 

a) I define the date dim like below
    {
        "name": "DATE", 
        "comment": "This is used as a template for other date dimensions.", 
        "label": "Update Date", 
        

        "role": "time",

        "levels": [
            {
                "name": "year", 
                "label": "Year"
            }, 
            {
                "name": "quarter", 
                "label": "Quarter"
            }, 
            {
                "name": "month", 
                "label": "Month"
            }, 
            {
                "name": "week", 
                "label": "Week"
            },
            {
                "name": "day", 
                "label": "Day"
            }
        ], 
        "hierarchies": [
            {
                "name": "weekly", 
                "label": "Weekly",
                "levels": ["year", "week"]
            } ,
            {
                "name": "monthly", 
                "label":"Monthly",
                "levels":["year", "quarter", "month"]
            } ,
            {
                "name": "daily", 
                "label":"Daily",
                "levels":["year", "month", "day" ]
            }

        ]
    },

When I choose daily->day to shown the daily result and show the picture report, the data will be sorted. I know I can export data to generate report by self. Just wonder if there is one way to avoid this. 

2015/3/1
2015/3/11
2015/3/12
2015/3/13
....
2015/3/19
2015/3/2
2015/3/21
....

![image](https://cloud.githubusercontent.com/assets/1400730/6959638/bac7b862-d94d-11e4-9e09-71c0aaa41e8c.png)

**Comment by jjmontesl** [comment]
Hello.

Can you please try using the "View > Horizontal Dimension" option instead? I think it should sort correctly, and the horizontal axis is more "natural" in CubesViewer for time-based dimensions.
