### ISSUE TITLE
update to django 1.8

### ISSUE THREAD

**Issue by auvipy** [jjmontesl/cubesviewer#45]

**Comment by jjmontesl** [comment]
Is there some way to support both Django 1.7 and 1.8?

**Comment by auvipy** [comment]
yes

**Comment by devvmh** [comment]
I'm not sure if this is done or what, but I've been using Django 1.8.5 to run cubesviewer for a few days now with no problems (well, there are some css problems sometimes, but that's probably not related to the Django version!)

**Comment by jjmontesl** [comment]
Thanks for the info. Closing this.
