### ISSUE TITLE
modify UI/UX to material views. by using django-materials.

### ISSUE THREAD

**Issue by auvipy** [jjmontesl/cubesviewer#46]
django-materials provide many built in stuff using which the look and feel of cube views could be greatly enhanced.

**Comment by jjmontesl** [comment]
Hi. CubesViewer itself is a pure Javascript library, and the Django application is an extension of it, however I cannot make CubesViewer dependant on any server-side library.

I agree that UI/UX needs a revamp. I have some stuff on the roadmap, but any help is greatly appreciated.
