### ISSUE TITLE
Cannot present series table: no measure has been selected

### ISSUE THREAD

**Issue by nagyv** [jjmontesl/cubesviewer#48]
Hi,

I'm running cubesviewer master with minor modification  (see #47). Cubesviewer seems to work fine, the model data is delivered to the webpage, but I can not get measures to have selected.

As a result when I would like to open a chart or series table view I get the following image.

![image](https://cloud.githubusercontent.com/assets/126671/9228520/23ed3938-4119-11e5-93f0-33048ba9e9a3.png)

How can I select measures?

**Comment by jjmontesl** [comment]
Measures can be selected from the View menu: View > Measure. This option appears only when you are in the Series or Chart mode. 

There is already a feature request in order to add a default measure (#29).

Let me know if this fixes the issue.
