### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by bitdivine** [jjmontesl/cubesviewer#49]
Hello,

I'm curious about your viewer but the demo isn't working.  Is there a chance that it could be fired up again?

Best wishes, Max

**Comment by declann** [comment]
+1

**Comment by jjmontesl** [comment]
Working on this.

**Comment by bitdivine** [comment]
Thanks! I'm looking forward to it.

**Comment by jjmontesl** [comment]
The demo site is back online.

**Comment by declann** [comment]
This is awesome, thanks Jose.

**Comment by bitdivine** [comment]
Awesome is exactly the word!  Thanks!  I've pinged it around our coding group!
