### ISSUE TITLE
analytical workspace examples throw an error

### ISSUE THREAD

**Issue by anandjeyahar** [jjmontesl/cubesviewer#51]
Hi,
  The current analytical workspace code seems to have some import error. 

 I tried this .. 
> from cubes import Workspace
>workspace = Workspace(config="slicer.ini")
>workspace.import_model("model.json")
>workspace.list_cubes()

And I get this error: 
<blockquote>
/home/anand/.virtualenvs/cubes/local/lib/python2.7/site-packages/cubes/workspace.pyc in list_cubes(self, identity)
    535         """
    536 
--> 537         all_cubes = self.namespace.list_cubes(recursive=True)
    538 
    539         if self.authorizer:

/home/anand/.virtualenvs/cubes/local/lib/python2.7/site-packages/cubes/namespace.pyc in list_cubes(self, recursive)
    112                 name = cube["name"]
    113                 if name in cube_names:
--> 114                     raise ModelError("Duplicate cube '%s'" % name)
    115                 cube_names.add(name)
    116 

NameError: global name 'ModelError' is not defined

</blockquote>

**Comment by jjmontesl** [comment]
The actual error here seems to be that you have two cubes with the same
name in your model ("Duplicate cube").

However, there also seems to be an error locating the ModelError class, and
the actual error is masked (we cannot see which cube is duplicated).

I suggest:

1) Check if all cubes in your model have different names.
2) If that doesn't help:
2.1) Are you using Cubes from master?
2.2) Does this happen with a stable 1.0.1? Current cubesviewer works with
1.0.1 (hasn't been tested with other Cubes version).

As a side note, note this message is tagged as [cubesviewer] but the issue
is strictly related to Cubes, so you may wish to change the subject.

Regards,



Jose Juan Montes

2015-10-27 8:47 GMT+01:00 anandjeyahar <notifications@github.com>:

**Comment by anandjeyahar** [comment]
Sorry about wrong tracker. I'll create in the original cubes repo.. And no I don't have two cubes with same name. It's version 1.0.1. 
Thanks
Anand
