### ISSUE TITLE
Make components into reusable angular directives

### ISSUE THREAD

**Issue by jjmontesl** [jjmontesl/cubesviewer#73]
Coming from #70, this moves to the top of the to-do list, only after map charts which is already in development. This ticket will take a some weeks to be resolved.

**Comment by pwalsh** [comment]
You might be interested in the approach we took on the feature/modern branch of Babbage.UI (which will soon become master).

We [componentized](https://github.com/openspending/babbage.ui/tree/feature/modern/src/components) all view logic, and then expose it via [Angular bindings](https://github.com/openspending/babbage.ui/tree/feature/modern/src/bindings/angular). 

While we are using Angular right now in OpenSpending, we did not want to limit reuse of our work to Angular, and so we've designed the code in such a way that bindings can be written for other frameworks. 

In fact, right now someone from the community is working on bindings for [vuewjs](https://vuejs.org)

**Comment by jjmontesl** [comment]
Closing as it won't be tackled shortly. Any future refactor should do this correctly, but the framework will surely change (either a newer Angular version or a different framework).
