### ISSUE TITLE
Incomplete output in facts table

### ISSUE THREAD

**Issue by Grigory75** [jjmontesl/cubesviewer#76]
When displaying facts table, some of attributes described in model.json are hidden. Model.json is here 
http://pastebin.com/jdNgqzns 

When issuing command 

curl "http://localhost:5000/cube/InvoiceLine/facts" 

output looks like this

[
    {
        "Invoice.InvoiceId": 1, 
        "InvoiceLine_InvoiceLineId": 1, 
        "Invoice.BillingAddress": "Theodor-Heuss-Stra\u00dfe 34", 
        "Invoice.InvoiceDate": "2009-01-01T00:00:00", 
        "Quantity": 1
    } 
]

but in browser facts tables contains only columns 
Id, InvoiceDate,Quantity.

How to display field BillingAddress?

WBW&R, Grigory

**Comment by jjmontesl** [comment]
You can see this data if you export facts. Is this enough or do you wish to have them in the facts view?

**Comment by Grigory75** [comment]
If it possible, I would like to have them in facts view, for example, combining with filter mode.

**Comment by Grigory75** [comment]
Please, explain me the pattern of how columns of facts table view selected. In my example, values of column "InvoiceData" displayed with "Invoice" label. I suppose, that the engine takes first column of each dimension in order of attribute list - is it so?

**Comment by jjmontesl** [comment]
- The first column is the fact ID.
- Next, for each dimension, a column is created for each level: the dimension level label attribute is shown (in its absence, the dimension level key will be used). 
- Finally, a column is created for each fact detail.

So, you are right, the list above does not include dimension _details_ (these are the dimension attributes that are not the key or the label).

I will look into adding this.

**Comment by jjmontesl** [comment]
Added dimension attributes. Please test with latest version.

Not sure if you wanted to see dimension keys, but that would bloat the Facts table. A "fact details" view is planned, which could show all the extra information (keys).

**Comment by Grigory75** [comment]
My previos installation had different directory strtucture (supposing 2.0.1 , I deployed it from github's zip-archive) - I ran command "manage.py runserver" to start web server. With new version 2.0.2, I followed new instruction and open in browser studio.html, but it was not enough - error message appears "Could not connect to server: Unknown error." . 

curl "http://localhost:5000/cubes" returns correct result - [
    {
        "category": null, 
        "info": {}, 
        "name": "Track", 
        "label": "Track"
    }
]

Couldn't you point me - what's wrong ?

**Comment by Grigory75** [comment]
Maybe, I should update slicer to last version? Now I use 1.0.1 release .

**Comment by jjmontesl** [comment]
No, I don't think slicer is involved. You should still use `manage.py runserver`. 

If you are using server, make sure you download the appropriate package (cubesviewer-server-2.0.2).

The other instructions are for the standalone HTML application.  I think you've downloaded the wrong package.

**Comment by Grigory75** [comment]
After cloning new cubesview server from git, I created virtualenv, activated it, started server .
Now in the floor part of browser window there is the text "CubesViewer 2.0.3-devel" . Shouldn't it be "2.0.2" ? Besides, when attempting to login I get error "attempt to write a readonly database" .

**Comment by Grigory75** [comment]
After cloning new cubesview server from git (git clone https://github.com/jjmontesl/cubesviewer-server.git
), I created virtualenv, activated it, started server .
Now in the floor part of browser window there is the text "CubesViewer 2.0.3-devel" . Shouldn't it be "2.0.2" ? Besides, when attempting to login I get error "attempt to write a readonly database" .

**Comment by jjmontesl** [comment]
`2.0.3-devel` is ok if you downloaded from master. ,Master contains latest release and some fixes. Next release will be `2.0.3`. Since you are testing bleeding edge features, you are ok using master.

Regading "could not connect to server", check what your browser says. You may have configured an incorrect Cubes URL (in settings.py) or your server may need to enable CORS access (check CubesViewer readme for that). It depends on what the browser says.

If you keep having this issue, please share the output of the browser console for the failed request.

**Comment by Grigory75** [comment]
"python manage.py runserver" output - http://pastebin.com/QTeTKVaG 
Slicer's output - http://pastebin.com/KQTfRR2s 
"curl "http://localhost:8000/cubesviewer/" outputs nothing

**Comment by jjmontesl** [comment]
The "locahost:5000" request is for Cubes. What you need to do is enable CORS support in Cubes. This is mentioned in CubesViewer release notes and also in the requirements section: https://github.com/jjmontesl/cubesviewer#requirements .

Regarding Django `runserver`, you can use `python manage.py runserver 0.0.0.0:8000` in order to listen in all interfaces, but that's not related to the CORS issue.

**Comment by gholay** [comment]
how to hide some columns in facts page  ?
