### ISSUE TITLE
CubesViewer Proxy User & ACL

### ISSUE THREAD

**Issue by jhramirez320** [jjmontesl/cubesviewer#88]
There is no documentation on how the Cubeviewers Proxy setup works and the proper configuration needed make the setting work properly. Can you please provide the back story and an example of the proper setup. Thanks!

**Comment by jjmontesl** [comment]
Hello. Do you refer to the CubesViewer Server feature (`CUBESVIEWER_CUBES_PROXY_USER`) or, in general, how to set up CubesViewer or CubesViewer Server behind a proxy?

The `CUBESVIEWER_CUBES_PROXY_USER` is meant to be used if CubesViewer Server is acting as a proxy for Cubes. From the client side,you would point CubesViewer cubes URL to: `http://cubesviewer-server/cubes/`. This will forward Cubes request to the server specified by `CUBESVIEWER_CUBES_URL` setting. 

This feature is however deprecated in favour of Cubes new authentication schemas, but those haven't been integrated by CubesViewer yet.

Can you further explain your use case?

**Comment by jhramirez320** [comment]
If the feature will be replaced, I don't have a question. Please provide documentation on the new authentication schema.
