### ISSUE TITLE
Export figure option results in an undefined output filename and corrupted PNG

### ISSUE THREAD

**Issue by pdsparks** [jjmontesl/cubesviewer#93]
The **export figure** option is not producing the desired output on my local development box (nor on the demo website at [cubesviewer.com](www.cubesviewer.com))  - instead of *cubename-chartype.png* the output is simply *undefined* with no extension type.

the **exportChartAsPNG** function appears to be using **exportService.saveAs** incorrectly by omitting the mime type at line **4199** of cubesviewer.js
```javascript
exportService.saveAs(canvasUrl, $scope.view.cube.name + "-" + $scope.view.params.charttype + ".png");
```
If we change this to add the mime type:
```javascript
exportService.saveAs(canvasUrl, "image/png", $scope.view.cube.name + "-" + $scope.view.params.charttype + ".png");
```
The output file now downloads with the correct name and file extension - however the file is “corrupted” unless we convert the utf-8 to an 8 bit unsigned integer as per this issue at [stackoverflow](https://stackoverflow.com/questions/17332071/trying-to-save-canvas-png-data-url-to-disk-with-html5-filesystem-but-when-i-ret):
```javascript
var data = atob( canvasUrl.substring( "data:image/png;base64,".length ) ), asArray = new Uint8Array(data.length);
for( var i = 0, len = data.length; i < len; ++i ) {asArray[i] = data.charCodeAt(i);}
var blob = new Blob( [ asArray.buffer ], {type: "image/png"} );
```
Then export the converted blob instead:
```javascript
exportService.saveAs(blob, "image/png", $scope.view.cube.name + "-" + $scope.view.params.charttype + ".png");
```
These modifications fix the issue for me and, hopefully, for others.

**Comment by jjmontesl** [comment]
Awesome! Thank you very much for this!

This has been fixed in commit 5ffdbf0. Available in master, will be included in next revision release.
