### ISSUE TITLE
Cubesviewer studio admin password

### ISSUE THREAD

**Issue by TenYearsGone** [jjmontesl/cubesviewer#96]
Sorry if this is a dumb question but...
Followed the instructions here https://github.com/jjmontesl/cubesviewer/blob/master/doc/guide/cubesviewer-server-installation.md
but at step 5 the "syncdb" argument has been replaced with 'migrate' and I did not get prompted for a user/password.
It seems to run fine but I am greeted with a CubesViewer Studio Server Login page. According to the doc if I am using sqllite I dont need a username and password - I haven't set this anywhere and I am not sure where to set it. Can someone help?

**Comment by jjmontesl** [comment]
You can create an administrator user using Django `createsuperuser` management command.

Check the docs: https://docs.djangoproject.com/en/2.0/ref/django-admin/#createsuperuser
